### ISSUE TITLE
preserveSymlink options not supported

### ISSUE THREAD

**Issue by magicdawn** [browserify/resolve#122]
see 

- https://nodejs.org/dist/latest-v7.x/docs/api/cli.html#cli_preserve_symlinks
- https://github.com/nodejs/node/blob/v7.7.4/lib/module.js#L13
- https://github.com/nodejs/node/blob/v7.7.4/lib/module.js#L129-L133

I add a sync version, but the async callback version is too complicated for me 😂 
https://github.com/magicdawn/node-resolve/commit/8bfeeccaf66d33c530ed2e373ab2138621e9500f

**Comment by ljharb** [comment]
This seems to have been added in node v6.3.0.

Based on your changes, it seems like since this module never calls `fs.realPath`, it's already preserving symlinks - what would be most helpful (more than your commit, which helps too) is failing sync and async test cases. With that, I could work on an implementation.

**Comment by ljharb** [comment]
`resolve` supports a `preserveSymlinks` option now; I'll be happy to reopen if that doesn't address this.
