### ISSUE TITLE
How to solve dynamic require errors

### ISSUE THREAD

**Issue by Nilesh0101** [browserify/resolve#141]
I'm using PKG tool for packaging nodejs application. Pkg uses Resolve module internally.
In my code there are some places where, what needs to be require is getting decided dynamically.
Problem is that Resolve could not resolve the values inside require statements.
Please refer below url for more information
https://github.com/zeit/pkg/issues/241

Thanks in Advance.

**Comment by ljharb** [comment]
`resolve` is a function; "static" and "dynamic" describes how the function is called, but it can not *possibly* change how the function works.

The error in the linked issue seems like it's coming from some build tool - it definitely isn't coming from node or this package, since it's impossible to know if a require is dynamic or not without static analysis.

**Comment by cancerberoSgx** [comment]
I'm using pck with browserify for solving this kind of problems since browserify is smarter and have well-defined rules and plugins for require(), something like this:

```
browserify myappindex.js --no-bundle-external  --no-builtins  -o bundle.js
pkg -t node8-linux -c pkg.json -o execfile bundle.js
```

I recommend pkg maintainers not to tacle the resolve problem and rely on browserify-like tool for building a bundle file like this

**Comment by Nilesh0101** [comment]
Thanks for the reply.
I will try using browserify.
