### ISSUE TITLE
Disable core packages

### ISSUE THREAD

**Issue by egormalyutin** [browserify/resolve#216]
Hello. Can I disable all core packages support?

**Comment by egormalyutin** [comment]
I already came up with hack like
```
if (require("resolve/lib/core.json")[pkg]) {
	pkg += "/"
}
console.log(pkg)
```

**Comment by ljharb** [comment]
What's your use case?

**Comment by ljharb** [comment]
also that check is very incorrect; use `require('resolve/lib/is-core')(pkg)`, if anything.

**Comment by egormalyutin** [comment]
@ljharb I just want to find modules installed in `node_modules` rather than core modules

**Comment by egormalyutin** [comment]
@ljharb Actually I used Object.property.hasOwnProperty and everything (it's just a short example), but thanks anyway!

**Comment by ljharb** [comment]
That’s not correct, though, because of the semver ranges. Use the isCore function.

You can do that by appending a slash, just like you can in node.

**Comment by egormalyutin** [comment]
@ljharb Okay, but can I _add_ core module to the list?

**Comment by ljharb** [comment]
Not without doing hacky unsupported things. What's your use case?

**Comment by egormalyutin** [comment]
@ljharb I'm trying to create a simple small module bundler.

Can I submit a PR with support of adding or removing core modules?

**Comment by ljharb** [comment]
browserify already is a simple small module bundler, and already uses `resolve` with existing options to achieve the same goal. If you can't use an existing bundler, i'd suggest reading how they do it :-)

I don't think a PR is warranted here.

**Comment by egormalyutin** [comment]
@ljharb I'm not trying to create a module bundled because I don't know how to use them, but because I want to understand more how they work

**Comment by arikon** [comment]
@ljharb My case is:
- I want to recursively copy all the dependencies, found in `package.json`
- one of the dependencies names is clashing with the core modules (`buffer` in my case), it is installed in `node_modules`
- `resolve` knows `buffer` as a core module, so it don't even try to find a module in `node_modules`, it's just returns `buffer`
- but I expected a full module path

**Comment by arikon** [comment]
I think the fix could be `isCore()` check happening after `loadNodeModulesSync()` call here:
https://github.com/browserify/resolve/blob/master/lib/sync.js#L88-L93

**Comment by octogonz** [comment]
> I think the fix could be `isCore()` check happening after `loadNodeModulesSync()` call here:
> https://github.com/browserify/resolve/blob/master/lib/sync.js#L88-L93

@arikon Hrmm.... I just tried the following test with Node 10:

```bash
$ npm init
$ npm install buffer
$ node -e console.log(require.resolve('buffer'))
```

It resolves to `"buffer"` instead of `"node_modules/buffer"`.  In other words, Node.js system modules seem to take precedence over installed NPM packages with the same name.  Thus perhaps `resolve.sync()` is handling this case accurately.

Which package did you find that depends on `"buffer"`? Does it import the system module and work correctly with that?  Or is it someone bypassing the Node.js module resolution? (In which case we may still want a `resolve` feature to disable/hook `isCore()`.)

**Comment by ljharb** [comment]
Indeed, this is correct. Only bundlers would use the installed one (which can be chosen via some function options you can read about in the readme); `buffer/` would be how you'd do it in node and resolve by default.

**Comment by arikon** [comment]
@octogonz `typeorm` depends on `buffer` package

**Comment by octogonz** [comment]
And I see they indeed do:
```
 window.Buffer = require("buffer/").Buffer;
```

**Comment by octogonz** [comment]
@ljharb In our case we are crawling `dependencies` and `devDependencies` from **package.json**.  So if a name appears in package.json, we can reasonably assume that it is meant to be an NPM package, not a system module. And we could handle this by always appending `/` before calling `resolve.sync()`. 

This solution feels slightly clumsy, though. It would be ideal if `resolve` provided an explicit option to disable `isCore()`.  Otherwise everywhere we do that, we have to include a code comment explaining the unfamiliar `/` suffix.  And we have to make sure the string doesn't already contain `/`, etc.

**Comment by ljharb** [comment]
You're right you'd need code like `inPackageJSON(x) && isCore(x) ? `${x}/` : x`, but that doesn't seem particularly troublesome?

**Comment by octogonz** [comment]
`` inPackageJSON(x) && isCore(x) ? `${x}/` : x `` isn't troublesome to write. Merely confusing for people who read the code later.

**Comment by octogonz** [comment]
Another problem is that the error messages come back like this:
```
ERROR: Cannot find module 'jquery/' from 'C:/my-project'
```
If I saw this error, my first thought would be "Oh, we must be accidentally appending a slash somewhere".

**Comment by ljharb** [comment]
Why would the slash be appended for a non-core module? or do you mean, in the case where you unconditionally append a slash.

**Comment by ljharb** [comment]
#233 has provided this.

**Comment by octogonz** [comment]
Thanks for implementing this!  We'll use it!

> or do you mean, in the case where you unconditionally append a slash.

Yes, to skip core modules we had to unconditionally append a slash, and then the resulting error message wouldn't make sense to users.
