### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by sgurin** [browserify/resolve#274]
Hi. Found missed close brasket in app/node_modules/resolve/test/resolver/malformed_package_json/package.json

Please take a look

![image](https://user-images.githubusercontent.com/25930200/151014872-9fac889f-d9f0-4c94-a6be-6934e00d94f3.png)

**Comment by ljharb** [comment]
Look at the file name. It's not missing, it's intentionally there.

Where are you getting this syntax error from? This file is a test fixture.

**Comment by sgurin** [comment]
Okay, add the whole directory in ignore for typescript checker. Now it warning 
![image](https://user-images.githubusercontent.com/25930200/151032101-e661200f-380a-417c-9c88-cd7e2ba2de8e.png)

**Comment by ljharb** [comment]
Why is typescript checking node_modules at all?

**Comment by sgurin** [comment]
Good question :) The same is why open bracket doing in package.json even for test :)

**Comment by ljharb** [comment]
Because `resolve` needs to test how it behaves when a dependency has a malformed package.json. It makes perfect sense for this package.

Typescript is a linter, like eslint. You should only be linting your own code, which doesn't include anything in node_modules.

Sounds like if you fix your TS settings it'll be resolved, so I'll close this.

(#271 is related; another tool improperly scanning things in node_modules)
