### ISSUE TITLE
Critical Vulnerability due to Resolve Package -- monorepo-symlink-test

### ISSUE THREAD

**Issue by kjcohen** [browserify/resolve#310]
Package causing vulnerability can be found below:

https://github.com/browserify/resolve/blob/main/test/resolver/multirepo/package.json

This is causing deployments to fail security screening due to the following:

https://snyk.io/advisor/npm-package/monorepo-symlink-test

**Comment by aashutoshrathi** [comment]
Hey! please refer to this: https://github.com/browserify/resolve/issues/309

**Comment by ljharb** [comment]
Because it's a private package that just coincidentally has the same name as the malicious one, it is a false positive - so whatever tool is flagging this repo is broken, and you should strongly reconsider using a tool that is this naive about npm package names.

Duplicate of https://github.com/browserify/resolve/issues/303. Duplicate of https://github.com/browserify/resolve/issues/291. Duplicate of https://github.com/browserify/resolve/issues/288. Duplicate of https://github.com/browserify/resolve/issues/304. Duplicate of #305. Duplicate of #306. Duplicate of #309.
