### ISSUE TITLE
Critical vulnerability monorepo-symlink-test 

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [browserify/resolve#311]
We are using AWS ERC scanner which doesn't support ignoring critical vulnerabilities.
I know that this is an edge case with a name matching `monorepo-symlink-test`.
Is it possible to rename this package name to something different? For ex `browserify-symlink-test`.

Thanks!

**Comment by ljharb** [comment]
Nope; I’m not going to rename a false positive just because a scanning tool was naive.

> Because it's a private package that just coincidentally has the same name as the malicious one, it is a false positive - so whatever tool is flagging this repo is broken, and you should strongly reconsider using a tool that is this naive about npm package names.

Duplicate of https://github.com/browserify/resolve/issues/303. Duplicate of https://github.com/browserify/resolve/issues/291. Duplicate of https://github.com/browserify/resolve/issues/288. Duplicate of https://github.com/browserify/resolve/issues/304. Duplicate of https://github.com/browserify/resolve/issues/305. Duplicate of https://github.com/browserify/resolve/issues/306. Duplicate of https://github.com/browserify/resolve/issues/309. Duplicate of #310.

**Comment by Iuriy-Budnikov** [comment]
If someone is faced with the same issue I would recommend deleting this file before running snyk.
It should help.

`rm app/node_modules/resolve/test/resolver/multirepo/package.json`
