### ISSUE TITLE
Package includes test folder

### ISSUE THREAD

**Issue by johnlister** [browserify/resolve#322]
The deployable package includes the test folder (presumably incorrectly). This also includes a number of dependencies that are flagged as containing critical security issues. For example monorepo-symlink-test.

Please remove the test folder from the deployed artifact

**Comment by ljharb** [comment]
It’s supposed to include it, and always will.

Also, that isn’t a dependency, it’s a false positive - any tool flagging that is incompetent and should not be used. Additionally, the latest v1 and v2 releases have renamed this test fixture so that incompetent security scanners can ignore it.

Just update your deps.

**Comment by Hronom** [comment]
@ljharb there pretty serious tools are reporting this, like AWS Inspector.

Is it possible to rename this test package(it's strange to have same name as vulnerable package) somehow to avoid unnecessary noise? (I'm from Java world, so can't help with npm and how it resolve dependency).
This help a lot.

**Comment by ljharb** [comment]
@Hronom this specific issue was worked around a long time ago; just upgrade your version of `resolve`.

**Comment by Hronom** [comment]
@ljharb thank you! Sorry for the noise, I will call it phantom noise.
