### ISSUE TITLE
Returns undefined for malformed JSON

### ISSUE THREAD

**Issue by rahatarmanahmed** [browserify/resolve#89]
``` shell
$ npm install resolve
$ echo "{" > package.json
$ node -e "require('resolve')('package.json', {moduleDirectory: '.'}, (err, res, pkg) => console.log(err, res, pkg))"
null '/Users/rahat/Downloads/temp/package.json' undefined
```

It should probably return an error about the JSON syntax error.

**Comment by iFedaka** [comment]
It's because this file: [async.js](https://github.com/substack/node-resolve/blob/master/lib/async.js)
ignores errors
```javascript
try { var pkg = JSON.parse(body) }
catch (err) {}
```

**Comment by ljharb** [comment]
This would be a breaking change - it still might be a good idea.

**Comment by davej** [comment]
Also ran into this while using `resolve` programmatically. I got the error:

```
async.js:157 Uncaught TypeError: Cannot read property 'main' of undefined
```

But the error was not raised in the error callback as expected, instead it crashed the application. I think this should be considered even though it's a breaking change because it causes a crash.

**Comment by ljharb** [comment]
@davej can you elaborate on your programmatic usage?

**Comment by davej** [comment]
@ljharb I use it to check if a dependency is installed and working. Something like this:

```js
import { promisify } from "util";
import resolveCB from "resolve";

const resolve = promisify(resolveCB);

const isModuleOk = async (dep, projectDirectory) => {
  try {
    await resolve(dep, { basedir: projectDirectory });
  } catch (err) {
    // Malformed JSON error is not thrown asynchronously
  }
};
```

**Comment by ljharb** [comment]
Thanks! (resolve isn’t trivially promisifiable, fwiw, because it receives more than one resolution argument)

**Comment by ljharb** [comment]
(To be clear, the `moduleDirectory` option isn't relevant to this issue)

I've written some tests I'll add to the v1.x branch that cover the current behavior (once i figure out how to get eslint not to error out on the malformed package.json). My current plan is to make a change in v2.x on the default branch, that instead of `undefined` here, you get the SyntaxError from failing to parse it.

**Comment by ljharb** [comment]
I'm not actually sure what the best fix is here.

The current change I'm making for v2 is that `readPackage`/`readPackageSync` will now be allowed to produce a SyntaxError, and that will be ignored, which simplifies the implementation of `readPackageSync` in particular.  However, this still would end up resolving something when package.json is malformed.

Since this is what node itself does - ignores a malformed package.json - I think this is the correct behavior, so I'm going to close this once I can land the tests I've written.
